** About disgrid

Simdata is a python library which enables access to simulation data of hydrodynamics planet disk interaction simulations.
Its main features are:

+ load data in a code independend way
  - the same line of code to load data for tool A or B
  - lets you focus on what you want to do with your data
+ automatically detecting the type of simulation code
  - no special book-keeping required to produce comparison plots

** Supported Hydrodynamics Codes

+ FargoCPT : custom version of the [[http://fargo.in2p3.fr/-Legacy-archive-][FARGO code]] which is used and maintained at the University of Tübingen.
+ [[http://fargo.in2p3.fr/][FARGO3D]] : GPU enabled version of the FARGO code supporting 3D calculations
+ [[http://plutocode.ph.unito.it/][PLUTO 4.2, 4.3]] : magneto-hydrodynamics code based on a Riemann solver

** Getting started

You need python3 to use this package!
Clone this repository and run =python3 setup.py install --user= to install the python package.
Navigate to an output directory of a simulation and enter a python shell and run:

#+begin_src python
from disgrid import Data
# load data from the current directory
d = Data()
# you can also specify a path
d = Data(path_to_data)
# show content of the data
print(d.fluids)
print(d.planets)
#+end_src

This will print the fluids (gas or dust species) and the planets which disgrid was able to find in your output directory.
